### ISSUE TITLE
NIvel 1. Paquetes para operaciones básicas sobre tablas

### ISSUE THREAD

**Issue by renardete** [garzuzo/DBProject#4]
Paquete para: Crear tabla, consultar tabla, actualizar un registro y eliminar la tabla.

- [x]  Cliente ( Sami)

- [x]  Producto ( Jonathan)

- [x]  Tipo producto (Juan)  

- [x]  Solicitud  (Landa)

- [x]  Tipo solicitud (Juan)

- [x]  Daño (Daniel)

- [x]  Tipo anomalia (Daniel)

- [x]  Funcionario (Ronal)

**Comment by danielq97** [comment]
Agrego PaqueteTipoAnomalia

**Comment by danielq97** [comment]
Agrego paquete Daño
